# Generated by Django 6.0.5 on 2026-05-16 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200, verbose_name='Nom événement')),
                ('type', models.CharField(choices=[('Art', 'Art'), ('Camping', 'Camping'), ('Conférence', 'Conférence'), ('Culture', 'Culture'), ('Formation', 'Formation'), ('Medical Convoy', 'Medical Convoy'), ('Table Ronde', 'Table Ronde'), ('Workshop', 'Workshop'), ('solidarity_donation', 'Solidarity — Donation'), ('solidarity_material', 'Solidarity — Material')], max_length=50, verbose_name='Type IA')),
                ('duration', models.CharField(max_length=20, verbose_name='Durée (ex: 2h, 24h)')),
                ('duration_h', models.FloatField(verbose_name='Durée en heures')),
                ('cost', models.FloatField(verbose_name='Coût réel (MAD)')),
                ('volunteers', models.IntegerField(verbose_name='Nombre de volontaires')),
                ('social_impact', models.FloatField(verbose_name='Impact social (0-1)')),
                ('cost_efficiency', models.FloatField(verbose_name='Efficacité coût (0-1)')),
                ('volunteer_intensity', models.FloatField(verbose_name='Intensité volontaires (0-1)')),
                ('priority_score', models.FloatField(verbose_name='Score de priorité (0-1)')),
                ('source_event_id', models.IntegerField(blank=True, help_text="ID de l'événement dans la table Event de tes coéquipiers", null=True, verbose_name='ID événement source (apps.events)')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ajouté le')),
                ('used_for_training', models.BooleanField(default=True, verbose_name='Utilisé pour entraînement')),
            ],
            options={
                'verbose_name': 'Historique IA',
                'verbose_name_plural': 'Historique IA',
                'db_table': 'ai_event_history',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='AITrainingRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Entraîné le')),
                ('total_events', models.IntegerField(verbose_name="Nombre d'événements utilisés")),
                ('cv_r2_mean', models.FloatField(verbose_name='CV-R² moyen')),
                ('cv_r2_std', models.FloatField(verbose_name='CV-R² écart-type')),
                ('triggered_by', models.CharField(blank=True, help_text="Nom de l'événement qui a déclenché le ré-entraînement", max_length=200, verbose_name='Déclenché par')),
            ],
            options={
                'verbose_name': 'Entraînement IA',
                'verbose_name_plural': 'Entraînements IA',
                'db_table': 'ai_training_run',
                'ordering': ['-trained_at'],
            },
        ),
    ]
